package elcon.mods.wikilink.api;

import java.util.List;

public interface ILinkType {

	/**
	 * @return Name for this link type, without spaces (example: MinecraftWiki)
	 */
	public String getName();
	
	/**
	 * @return List of accepted topics (example: [ItemStack.class, Entity.class])
	 */
	public List<Class<?>> getTopics();
	
	/**
	 * @return Whether this link type search only? (example: Google: true, MinecraftWiki: false)
	 */
	public boolean isSearchOnly();
	
	/**
	 * Generate a search link for a topic
	 * 
	 * @param topic The object to generate a search link for (example: ItemStack)
	 * @return The URL generated by this link type for the topic (example: http://google.com/search?q=test)
	 */
	public String generateSearchLink(Object topic);
	
	/**
	 * Generate a link for a topic
	 * 
	 * @param topic The object to generate a link for (example: ItemStack)
	 * @return The URL generated by this link type for the topic or null if the topic doesn't exist (example: http://google.com/search?q=test)
	 */
	public String generateLink(Object topic);
}
