package elcon.mods.wikilink;

import java.io.File;

import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.common.config.Property;

public class WLConfig {

	public static final String CATEGORY_GENERAL = "general";
	public static final String CATEGORY_LINK_TYPES = "linktypes";
	
	public Configuration config;

	public static boolean showTooltipsOnItems = true;
	public static boolean shortenLinks = true;

	public WLConfig(Configuration config) {
		this.config = config;
	}

	public WLConfig(File config) {
		this(new Configuration(config));
	}

	public void load() {
		config.load();

		showTooltipsOnItems = config.get(CATEGORY_GENERAL, "showTooltipsOnItems", showTooltipsOnItems, "Display WikiLink tooltip when hovering over items").getBoolean(showTooltipsOnItems);
		shortenLinks = config.get(CATEGORY_GENERAL, "shortenLinks", shortenLinks, "Use bit.ly to shorten links generated by WikiLink").getBoolean(shortenLinks);
	}

	public void save() {
		config.save();
	}
	
	public Property get(String category, String key) {
		if(config.getCategoryNames().contains(category)) {
			if(config.getCategory(category).containsKey(category)) {
				return config.getCategory(category).get(key);
			}
		}
		return null;
	}
	
	public void set(String category, String key, String value) {
		if(config.getCategoryNames().contains(category)) {
			if(config.getCategory(category).containsKey(category)) {
				config.getCategory(category).get(key).set(value);
			}
		} else {
			config.get(category, key, value);
		}
		config.save();
	}
}
